<a href="https://colab.research.google.com/github/darshbaxi/Emoji_prediction/blob/main/EMOJI_PREDICTION.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import tensorflow as tf
import keras

In [2]:
df=pd.read_csv('Train.csv')

In [3]:
df.head()

Unnamed: 0                                               TEXT  Label
0           0  Vacation wasted ! #vacation2017 #photobomb #ti...      0
1           1  Oh Wynwood, you’re so funny! : @user #Wynwood ...      1
2           2  Been friends since 7th grade. Look at us now w...      2
3           3  This is what it looks like when someone loves ...      3
4           4  RT @user this white family was invited to a Bl...      3

In [4]:
df=df.iloc[:,1:]

In [5]:
x=df['TEXT']

In [6]:
y=df['Label']

In [7]:
y

0         0
1         1
2         2
3         3
4         3
         ..
69995     3
69996    16
69997     2
69998     3
69999    14
Name: Label, Length: 70000, dtype: int64

In [8]:
import nltk


from nltk.stem import PorterStemmer as ps
from nltk.stem import WordNetLemmatizer as wl
from nltk.corpus import stopwords

lammtizer=wl()
nltk.download('wordnet')
nltk.download('stopwords')
stemmer=ps()
nltk.download('punkt')


[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


True

In [9]:

import re
fin=[]
for i in range(len(df)):
  review=re.sub('[^a-zA-Z]',' ',x[i])
  review=review.lower()
  word=nltk.word_tokenize(review)
  arr=[]
  for j in word:
    if j not in set(stopwords.words('english')):
      arr.append(lammtizer.lemmatize(j))
  review=' '.join(arr)
  fin.append(review)


In [ ]:
fin

In [41]:
from keras.preprocessing.text import one_hot
onrhot=[one_hot(word,520000) for word in fin]

In [12]:
def get_maxlen(fina):
    maxlen = 0
    for sent in fina:
        maxlen = max(maxlen, len(sent))
    return maxlen

max_len = get_maxlen(fin)
print(max_len)

127


In [35]:
a=[]
def get_words(fina):
  for sen in fina:
    word=nltk.word_tokenize(sen)
    for j in word:
      a.append(j)

In [37]:
get_words(fin)

In [40]:
len(a)

514629

In [42]:
from tensorflow.keras.preprocessing.sequence import pad_sequences
docs=pad_sequences(onrhot,padding='post',maxlen=max_len)

In [43]:
docs

array([[ 31289,  26552,  31289, ...,      0,      0,      0],
       [321798, 310146, 255554, ...,      0,      0,      0],
       [423048, 462099, 137029, ...,      0,      0,      0],
       ...,
       [171410, 344672, 191413, ...,      0,      0,      0],
       [190560, 286519, 345689, ...,      0,      0,      0],
       [238059, 270646,   2610, ...,      0,      0,      0]], dtype=int32)

In [44]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense

In [98]:
model = Sequential([
    Embedding(input_dim = 520000,
              output_dim = 100,
              input_length = max_len,
             ),
    LSTM(units = 100),
    Dense(20, activation = 'softmax')
])

model.compile(optimizer = 'adam', loss = 'categorical_crossentropy', metrics = ['accuracy'])

In [99]:
model.summary()

Model: "sequential_11"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_10 (Embedding)    (None, 127, 100)          52000000  
                                                                 
 lstm_12 (LSTM)              (None, 100)               80400     
                                                                 
 dense_12 (Dense)            (None, 20)                2020      
                                                                 
Total params: 52,082,420
Trainable params: 52,082,420
Non-trainable params: 0
_________________________________________________________________


In [100]:
x_train=np.array(docs)

In [101]:
x_train

array([[ 31289,  26552,  31289, ...,      0,      0,      0],
       [321798, 310146, 255554, ...,      0,      0,      0],
       [423048, 462099, 137029, ...,      0,      0,      0],
       ...,
       [171410, 344672, 191413, ...,      0,      0,      0],
       [190560, 286519, 345689, ...,      0,      0,      0],
       [238059, 270646,   2610, ...,      0,      0,      0]], dtype=int32)

In [102]:
y_tarin=np.array(y)
y_tarin

array([ 0,  1,  2, ...,  2,  3, 14])

In [103]:
y_tarin.shape,x_train.shape

((70000,), (70000, 127))